version: "3"

services:
    app:
        image: ruby:3.2.2
        working_dir: /app
        volumes:
            - ./app:/app
        # env_file:
        #     - .env
        ports:
            - "8000:8000"
        command: >
            bash -c "
            rm -f tmp/pids/server.pid &&
            bundle install &&
            bundle exec rails s -b '0.0.0.0' -p 8000"
